### ISSUE TITLE
[CSS] CSS 去掉点li 的点

### ISSUE THREAD

**Issue by david2tdw** [david2tdw/blog#31]
方法一：
```css
<ul>
     <li style="list-style-type:none;">百度</li>
     <li style="list-style-type:none;">雅虎</li>
     <li style="list-style-type:none;">新浪</li>
     <li style="list-style-type:none;">谷歌</li>
</ul>
```

方法二：
```css
<style>
li {list-style-type:none;}
</style>
<ul>
     <li>百度</li>
     <li>雅虎</li>
     <li>新浪</li>
     <li>谷歌</li>
</ul>
```

方法三：
``` css
<style>
.li_style {list-style-type:none;}
</style>
<ul>
     <li class="li_style">百度</li>
     <li class="li_style">雅虎</li>
     <li class="li_style">新浪</li>
     <li class="li_style">谷歌</li>
</ul>
```

[参考](http://blog.sina.com.cn/s/blog_63b13c300100jyek.html)
